name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18.x"]
        os: [ubuntu-latest]

    steps:
      - name: Lint
        run: bun lint

      - name: Build
        run: bun build
